paths:
  input: /home/ubuntu/Dropbox/Videos_LeftCamera/
  output: /home/ubuntu/saandeep/openface_extractor/output/DISFA/Left_camera/

params:
  type: videos
  ext: avi

docker:
  img: openface
  work_dir: /home/openface-build
  cmd: ./build/bin/FeatureExtraction